[platformio]

default_envs = test_audio

; Entorno principal de desarrollo — audio + display + sensores
[env:test_audio]
platform        = espressif32
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
upload_speed    = 460800
build_flags     = -I include
build_src_filter = -<*> +<../src_audio/*>
extra_scripts   = pre:scripts/close_monitor.py
lib_deps =
    majicDesigns/MD_Parola @ ^3.7.3
    majicDesigns/MD_MAX72XX @ ^3.5.1

; Entorno para probar encoder KY-040 (CLK=32, DT=33, SW=25)
[env:test_encoder]
platform         = espressif32
board            = esp32dev
framework        = arduino
monitor_speed    = 115200
upload_speed     = 460800
build_src_filter = -<*> +<../src_encoder/*>
extra_scripts    = pre:scripts/close_monitor.py
