[platformio]
src_dir = src

[env:esp32dev]
platform        = espressif32
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
upload_speed    = 460800
build_flags     = -I include
extra_scripts   = pre:scripts/close_monitor.py
lib_deps =
    majicDesigns/MD_Parola @ ^3.7.3
    majicDesigns/MD_MAX72XX @ ^3.5.1
    ; DFRobotDFPlayerMini eliminada — clones rechazan checksum, usamos raw serial

; Entorno principal de desarrollo — audio + display + sensores
[env:test_audio]
platform        = espressif32
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
upload_speed    = 460800
build_flags     = -I include
build_src_filter = -<*> +<../src_audio/*>
extra_scripts   = pre:scripts/close_monitor.py
lib_deps =
    majicDesigns/MD_Parola @ ^3.7.3
    majicDesigns/MD_MAX72XX @ ^3.5.1

; Entorno para simulacion Wokwi — igual al anterior pero con flag WOKWI_SIM
; El audio queda deshabilitado y se loguea por Serial
[env:wokwi]
platform        = espressif32
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
build_flags     =
    -I include
    -D WOKWI_SIM
lib_deps =
    majicDesigns/MD_Parola @ ^3.7.3
    majicDesigns/MD_MAX72XX @ ^3.5.1
